/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cinema;

/**
 *
 * @author christinecarylchen
 */
public class TYA extends javax.swing.JFrame {

    /** Creates new form TYA */
    public TYA() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTYA = new javax.swing.JPanel();
        TYApanelSpiderMan = new javax.swing.JPanel();
        TYAdetailSpiderMan = new javax.swing.JButton();
        TYAbuttonSpiderMan = new javax.swing.JButton();
        TYApanelschedSpiderMan = new javax.swing.JPanel();
        TYAlabelSpiderMan = new javax.swing.JLabel();
        TYAlabelGenreSpiderMan = new javax.swing.JLabel();
        TYAlabelRTimeSpiderMan = new javax.swing.JLabel();
        TYAlabelSchedSpiderMan = new javax.swing.JLabel();
        TYAbuttonReserveSpiderMan = new javax.swing.JButton();
        TYAlabelShowSpiderMan = new javax.swing.JLabel();
        TYACars = new javax.swing.JPanel();
        TYAdetailCars = new javax.swing.JButton();
        TYAbuttonCars = new javax.swing.JButton();
        TYApanelschedCars = new javax.swing.JPanel();
        TYAlabelCars = new javax.swing.JLabel();
        TYAlabelGenreCars = new javax.swing.JLabel();
        TYAlabelRTimeCars = new javax.swing.JLabel();
        TYAlabelSchedCars = new javax.swing.JLabel();
        TYAbuttonReserveCars = new javax.swing.JButton();
        TYAlabelShowCars = new javax.swing.JLabel();
        TYApanelRoughNight = new javax.swing.JPanel();
        TYAdetailRoughNight = new javax.swing.JButton();
        TYAbuttonRoughNight = new javax.swing.JButton();
        TYApanelschedSpiderMan3 = new javax.swing.JPanel();
        TYAlabelRoughNight = new javax.swing.JLabel();
        TYAlabelGenreRoughNight = new javax.swing.JLabel();
        TYAlabelRTimeRoughNight = new javax.swing.JLabel();
        TYAlabelSchedRoughNight = new javax.swing.JLabel();
        TYAbuttonReserveRoughNight = new javax.swing.JButton();
        TYAlabelShowRoughNight = new javax.swing.JLabel();
        TYApanelWonderWoman = new javax.swing.JPanel();
        TYAdetailWonderWoman = new javax.swing.JButton();
        TYAbuttonWonderWoman = new javax.swing.JButton();
        TYApanelschedWonderWoman = new javax.swing.JPanel();
        TYAlabelWonderWoman = new javax.swing.JLabel();
        TYAlabelGenreWonderWoman = new javax.swing.JLabel();
        TYAlabelRTimeWonderWoman = new javax.swing.JLabel();
        TYAlabelSchedWonderWoman = new javax.swing.JLabel();
        TYAbuttonReserveWonderWoman = new javax.swing.JButton();
        TYAlabelShowWonderWoman = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TYApanelSpiderMan.setBackground(new java.awt.Color(255, 255, 255));

        TYAdetailSpiderMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        TYAdetailSpiderMan.setBorderPainted(false);
        TYAdetailSpiderMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYAdetailSpiderManActionPerformed(evt);
            }
        });

        TYAbuttonSpiderMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterSpiderman.png"))); // NOI18N
        TYAbuttonSpiderMan.setBorderPainted(false);
        TYAbuttonSpiderMan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonSpiderManPressed.png"))); // NOI18N
        TYAbuttonSpiderMan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonSpiderManRollover.png"))); // NOI18N

        TYApanelschedSpiderMan.setBackground(new java.awt.Color(255, 255, 255));

        TYAlabelSpiderMan.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        TYAlabelSpiderMan.setForeground(new java.awt.Color(34, 66, 180));
        TYAlabelSpiderMan.setText("SPIDER-MAN: HOMECOMING");

        TYAlabelGenreSpiderMan.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelGenreSpiderMan.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelGenreSpiderMan.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelGenreSpiderMan.setText("FANTASY | SCIENCE FICTION");

        TYAlabelRTimeSpiderMan.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelRTimeSpiderMan.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelRTimeSpiderMan.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelRTimeSpiderMan.setText("2 HOURS 13 MINUTES");

        TYAlabelSchedSpiderMan.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelSchedSpiderMan.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        TYAlabelSchedSpiderMan.setForeground(new java.awt.Color(249, 115, 0));
        TYAlabelSchedSpiderMan.setText("SCHEDULE:");

        TYAbuttonReserveSpiderMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        TYAbuttonReserveSpiderMan.setBorder(null);
        TYAbuttonReserveSpiderMan.setBorderPainted(false);
        TYAbuttonReserveSpiderMan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        TYAbuttonReserveSpiderMan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        TYAlabelShowSpiderMan.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelShowSpiderMan.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelShowSpiderMan.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelShowSpiderMan.setText("12:30 PM");

        javax.swing.GroupLayout TYApanelschedSpiderManLayout = new javax.swing.GroupLayout(TYApanelschedSpiderMan);
        TYApanelschedSpiderMan.setLayout(TYApanelschedSpiderManLayout);
        TYApanelschedSpiderManLayout.setHorizontalGroup(
            TYApanelschedSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelschedSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TYApanelschedSpiderManLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TYApanelschedSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TYAlabelSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TYAlabelGenreSpiderMan)
                            .addComponent(TYAlabelRTimeSpiderMan)
                            .addComponent(TYAlabelSchedSpiderMan)
                            .addComponent(TYAbuttonReserveSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(TYApanelschedSpiderManLayout.createSequentialGroup()
                        .addComponent(TYAlabelShowSpiderMan)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TYApanelschedSpiderManLayout.setVerticalGroup(
            TYApanelschedSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TYAlabelSpiderMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelGenreSpiderMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelRTimeSpiderMan)
                .addGap(26, 26, 26)
                .addComponent(TYAlabelSchedSpiderMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelShowSpiderMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TYAbuttonReserveSpiderMan))
        );

        javax.swing.GroupLayout TYApanelSpiderManLayout = new javax.swing.GroupLayout(TYApanelSpiderMan);
        TYApanelSpiderMan.setLayout(TYApanelSpiderManLayout);
        TYApanelSpiderManLayout.setHorizontalGroup(
            TYApanelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYAbuttonSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYAdetailSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYApanelschedSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TYApanelSpiderManLayout.setVerticalGroup(
            TYApanelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYApanelschedSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TYApanelSpiderManLayout.createSequentialGroup()
                        .addComponent(TYAbuttonSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TYAdetailSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TYACars.setBackground(new java.awt.Color(255, 255, 255));

        TYAdetailCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonG.png"))); // NOI18N
        TYAdetailCars.setBorderPainted(false);
        TYAdetailCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYAdetailCarsActionPerformed(evt);
            }
        });

        TYAbuttonCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterCars3.png"))); // NOI18N
        TYAbuttonCars.setBorderPainted(false);
        TYAbuttonCars.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonCars3Pressed.png"))); // NOI18N
        TYAbuttonCars.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonCars3Rollover.png"))); // NOI18N

        TYApanelschedCars.setBackground(new java.awt.Color(255, 255, 255));

        TYAlabelCars.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        TYAlabelCars.setForeground(new java.awt.Color(34, 66, 180));
        TYAlabelCars.setText("CARS 3");

        TYAlabelGenreCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelGenreCars.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelGenreCars.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelGenreCars.setText("SPORT | ACTION");

        TYAlabelRTimeCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelRTimeCars.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelRTimeCars.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelRTimeCars.setText("1 HOUR 49 MINUTES");
        TYAlabelRTimeCars.setToolTipText("");

        TYAlabelSchedCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelSchedCars.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        TYAlabelSchedCars.setForeground(new java.awt.Color(249, 115, 0));
        TYAlabelSchedCars.setText("SCHEDULE:");

        TYAbuttonReserveCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        TYAbuttonReserveCars.setBorder(null);
        TYAbuttonReserveCars.setBorderPainted(false);
        TYAbuttonReserveCars.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        TYAbuttonReserveCars.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        TYAlabelShowCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelShowCars.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelShowCars.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelShowCars.setText("12:30 PM");

        javax.swing.GroupLayout TYApanelschedCarsLayout = new javax.swing.GroupLayout(TYApanelschedCars);
        TYApanelschedCars.setLayout(TYApanelschedCarsLayout);
        TYApanelschedCarsLayout.setHorizontalGroup(
            TYApanelschedCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelschedCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TYApanelschedCarsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TYApanelschedCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TYAlabelCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TYAlabelGenreCars)
                            .addComponent(TYAlabelRTimeCars)
                            .addComponent(TYAlabelSchedCars)
                            .addComponent(TYAbuttonReserveCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(TYApanelschedCarsLayout.createSequentialGroup()
                        .addComponent(TYAlabelShowCars)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TYApanelschedCarsLayout.setVerticalGroup(
            TYApanelschedCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TYAlabelCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelGenreCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelRTimeCars)
                .addGap(26, 26, 26)
                .addComponent(TYAlabelSchedCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelShowCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TYAbuttonReserveCars)
                .addContainerGap())
        );

        javax.swing.GroupLayout TYACarsLayout = new javax.swing.GroupLayout(TYACars);
        TYACars.setLayout(TYACarsLayout);
        TYACarsLayout.setHorizontalGroup(
            TYACarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYACarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYACarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYAbuttonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYAdetailCars, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYApanelschedCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TYACarsLayout.setVerticalGroup(
            TYACarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYACarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TYAbuttonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAdetailCars, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(TYApanelschedCars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TYApanelRoughNight.setBackground(new java.awt.Color(255, 255, 255));

        TYAdetailRoughNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR16.png"))); // NOI18N
        TYAdetailRoughNight.setBorderPainted(false);
        TYAdetailRoughNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYAdetailRoughNightActionPerformed(evt);
            }
        });

        TYAbuttonRoughNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterRoughNight.png"))); // NOI18N
        TYAbuttonRoughNight.setBorderPainted(false);
        TYAbuttonRoughNight.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonRoughNightPressed.png"))); // NOI18N
        TYAbuttonRoughNight.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonRoughNightRollover.png"))); // NOI18N

        TYApanelschedSpiderMan3.setBackground(new java.awt.Color(255, 255, 255));

        TYAlabelRoughNight.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        TYAlabelRoughNight.setForeground(new java.awt.Color(34, 66, 180));
        TYAlabelRoughNight.setText("ROUGH NIGHT");

        TYAlabelGenreRoughNight.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelGenreRoughNight.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelGenreRoughNight.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelGenreRoughNight.setText("COMEDY");

        TYAlabelRTimeRoughNight.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelRTimeRoughNight.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelRTimeRoughNight.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelRTimeRoughNight.setText("1 HOUR 53 MINUTES");

        TYAlabelSchedRoughNight.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelSchedRoughNight.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        TYAlabelSchedRoughNight.setForeground(new java.awt.Color(249, 115, 0));
        TYAlabelSchedRoughNight.setText("SCHEDULE:");

        TYAbuttonReserveRoughNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        TYAbuttonReserveRoughNight.setBorder(null);
        TYAbuttonReserveRoughNight.setBorderPainted(false);
        TYAbuttonReserveRoughNight.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        TYAbuttonReserveRoughNight.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        TYAlabelShowRoughNight.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelShowRoughNight.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelShowRoughNight.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelShowRoughNight.setText("05:05 PM");

        javax.swing.GroupLayout TYApanelschedSpiderMan3Layout = new javax.swing.GroupLayout(TYApanelschedSpiderMan3);
        TYApanelschedSpiderMan3.setLayout(TYApanelschedSpiderMan3Layout);
        TYApanelschedSpiderMan3Layout.setHorizontalGroup(
            TYApanelschedSpiderMan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedSpiderMan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelschedSpiderMan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TYApanelschedSpiderMan3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TYApanelschedSpiderMan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TYAlabelRoughNight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TYAlabelGenreRoughNight)
                            .addComponent(TYAlabelRTimeRoughNight)
                            .addComponent(TYAlabelSchedRoughNight)
                            .addComponent(TYAbuttonReserveRoughNight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(TYApanelschedSpiderMan3Layout.createSequentialGroup()
                        .addComponent(TYAlabelShowRoughNight)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TYApanelschedSpiderMan3Layout.setVerticalGroup(
            TYApanelschedSpiderMan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedSpiderMan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TYAlabelRoughNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelGenreRoughNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelRTimeRoughNight)
                .addGap(26, 26, 26)
                .addComponent(TYAlabelSchedRoughNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelShowRoughNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TYAbuttonReserveRoughNight))
        );

        javax.swing.GroupLayout TYApanelRoughNightLayout = new javax.swing.GroupLayout(TYApanelRoughNight);
        TYApanelRoughNight.setLayout(TYApanelRoughNightLayout);
        TYApanelRoughNightLayout.setHorizontalGroup(
            TYApanelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelRoughNightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYAbuttonRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYAdetailRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYApanelschedSpiderMan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TYApanelRoughNightLayout.setVerticalGroup(
            TYApanelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelRoughNightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYApanelschedSpiderMan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TYApanelRoughNightLayout.createSequentialGroup()
                        .addComponent(TYAbuttonRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TYAdetailRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TYApanelWonderWoman.setBackground(new java.awt.Color(255, 255, 255));

        TYAdetailWonderWoman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        TYAdetailWonderWoman.setBorderPainted(false);
        TYAdetailWonderWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYAdetailWonderWomanActionPerformed(evt);
            }
        });

        TYAbuttonWonderWoman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterWonderWoman.png"))); // NOI18N
        TYAbuttonWonderWoman.setBorderPainted(false);
        TYAbuttonWonderWoman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonWonderWomanPressed.png"))); // NOI18N
        TYAbuttonWonderWoman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonWonderWomanRollover.png"))); // NOI18N

        TYApanelschedWonderWoman.setBackground(new java.awt.Color(255, 255, 255));

        TYAlabelWonderWoman.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        TYAlabelWonderWoman.setForeground(new java.awt.Color(34, 66, 180));
        TYAlabelWonderWoman.setText("WONDER WOMAN");

        TYAlabelGenreWonderWoman.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelGenreWonderWoman.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelGenreWonderWoman.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelGenreWonderWoman.setText("FANTASY | SCIENCE FICTION");

        TYAlabelRTimeWonderWoman.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelRTimeWonderWoman.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelRTimeWonderWoman.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelRTimeWonderWoman.setText("2 HOURS 21 MINUTES");

        TYAlabelSchedWonderWoman.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelSchedWonderWoman.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        TYAlabelSchedWonderWoman.setForeground(new java.awt.Color(249, 115, 0));
        TYAlabelSchedWonderWoman.setText("SCHEDULE:");

        TYAbuttonReserveWonderWoman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        TYAbuttonReserveWonderWoman.setBorder(null);
        TYAbuttonReserveWonderWoman.setBorderPainted(false);
        TYAbuttonReserveWonderWoman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        TYAbuttonReserveWonderWoman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        TYAlabelShowWonderWoman.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelShowWonderWoman.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelShowWonderWoman.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelShowWonderWoman.setText("07:15 PM");

        javax.swing.GroupLayout TYApanelschedWonderWomanLayout = new javax.swing.GroupLayout(TYApanelschedWonderWoman);
        TYApanelschedWonderWoman.setLayout(TYApanelschedWonderWomanLayout);
        TYApanelschedWonderWomanLayout.setHorizontalGroup(
            TYApanelschedWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelschedWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TYApanelschedWonderWomanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TYApanelschedWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TYAlabelWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TYAlabelGenreWonderWoman)
                            .addComponent(TYAlabelRTimeWonderWoman)
                            .addComponent(TYAlabelSchedWonderWoman)
                            .addComponent(TYAbuttonReserveWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(TYApanelschedWonderWomanLayout.createSequentialGroup()
                        .addComponent(TYAlabelShowWonderWoman)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TYApanelschedWonderWomanLayout.setVerticalGroup(
            TYApanelschedWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelschedWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TYAlabelWonderWoman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelGenreWonderWoman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelRTimeWonderWoman)
                .addGap(26, 26, 26)
                .addComponent(TYAlabelSchedWonderWoman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelShowWonderWoman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TYAbuttonReserveWonderWoman))
        );

        javax.swing.GroupLayout TYApanelWonderWomanLayout = new javax.swing.GroupLayout(TYApanelWonderWoman);
        TYApanelWonderWoman.setLayout(TYApanelWonderWomanLayout);
        TYApanelWonderWomanLayout.setHorizontalGroup(
            TYApanelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYAbuttonWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYAdetailWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYApanelschedWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TYApanelWonderWomanLayout.setVerticalGroup(
            TYApanelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TYApanelWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TYApanelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYApanelschedWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TYApanelWonderWomanLayout.createSequentialGroup()
                        .addComponent(TYAbuttonWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TYAdetailWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTYALayout = new javax.swing.GroupLayout(panelTYA);
        panelTYA.setLayout(panelTYALayout);
        panelTYALayout.setHorizontalGroup(
            panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTYALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYApanelSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYApanelRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYACars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYApanelWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panelTYALayout.setVerticalGroup(
            panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTYALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TYApanelSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TYACars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelTYALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TYApanelRoughNight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TYApanelWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTYA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelTYA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TYAdetailSpiderManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYAdetailSpiderManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TYAdetailSpiderManActionPerformed

    private void TYAdetailCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYAdetailCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TYAdetailCarsActionPerformed

    private void TYAdetailRoughNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYAdetailRoughNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TYAdetailRoughNightActionPerformed

    private void TYAdetailWonderWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYAdetailWonderWomanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TYAdetailWonderWomanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TYA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TYACars;
    private javax.swing.JButton TYAbuttonCars;
    private javax.swing.JButton TYAbuttonReserveCars;
    private javax.swing.JButton TYAbuttonReserveRoughNight;
    private javax.swing.JButton TYAbuttonReserveSpiderMan;
    private javax.swing.JButton TYAbuttonReserveWonderWoman;
    private javax.swing.JButton TYAbuttonRoughNight;
    private javax.swing.JButton TYAbuttonSpiderMan;
    private javax.swing.JButton TYAbuttonWonderWoman;
    private javax.swing.JButton TYAdetailCars;
    private javax.swing.JButton TYAdetailRoughNight;
    private javax.swing.JButton TYAdetailSpiderMan;
    private javax.swing.JButton TYAdetailWonderWoman;
    private javax.swing.JLabel TYAlabelCars;
    private javax.swing.JLabel TYAlabelGenreCars;
    private javax.swing.JLabel TYAlabelGenreRoughNight;
    private javax.swing.JLabel TYAlabelGenreSpiderMan;
    private javax.swing.JLabel TYAlabelGenreWonderWoman;
    private javax.swing.JLabel TYAlabelRTimeCars;
    private javax.swing.JLabel TYAlabelRTimeRoughNight;
    private javax.swing.JLabel TYAlabelRTimeSpiderMan;
    private javax.swing.JLabel TYAlabelRTimeWonderWoman;
    private javax.swing.JLabel TYAlabelRoughNight;
    private javax.swing.JLabel TYAlabelSchedCars;
    private javax.swing.JLabel TYAlabelSchedRoughNight;
    private javax.swing.JLabel TYAlabelSchedSpiderMan;
    private javax.swing.JLabel TYAlabelSchedWonderWoman;
    private javax.swing.JLabel TYAlabelShowCars;
    private javax.swing.JLabel TYAlabelShowRoughNight;
    private javax.swing.JLabel TYAlabelShowSpiderMan;
    private javax.swing.JLabel TYAlabelShowWonderWoman;
    private javax.swing.JLabel TYAlabelSpiderMan;
    private javax.swing.JLabel TYAlabelWonderWoman;
    private javax.swing.JPanel TYApanelRoughNight;
    private javax.swing.JPanel TYApanelSpiderMan;
    private javax.swing.JPanel TYApanelWonderWoman;
    private javax.swing.JPanel TYApanelschedCars;
    private javax.swing.JPanel TYApanelschedSpiderMan;
    private javax.swing.JPanel TYApanelschedSpiderMan3;
    private javax.swing.JPanel TYApanelschedWonderWoman;
    private javax.swing.JPanel panelTYA;
    // End of variables declaration//GEN-END:variables

}
