/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

/**
 *
 * @author christinecarylchen
 */
public class WSLT extends javax.swing.JFrame {

    /**
     * Creates new form WSLT
     */
    public WSLT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWSLT = new javax.swing.JPanel();
        WSLTAmity = new javax.swing.JPanel();
        WSLTdetailAmity = new javax.swing.JButton();
        WSLTbuttonAmity = new javax.swing.JButton();
        WSLTpanelschedAmity = new javax.swing.JPanel();
        WSLTlabelAmity = new javax.swing.JLabel();
        WSLTlabelGenreAmity = new javax.swing.JLabel();
        WSLTlabelRTimeAmity = new javax.swing.JLabel();
        WSLTlabelSchedAmity = new javax.swing.JLabel();
        WSLTbuttonReserveAmity = new javax.swing.JButton();
        WSLTlabelShowAmity = new javax.swing.JLabel();
        WSLTJohnWick = new javax.swing.JPanel();
        WSLTdetailJohnWick = new javax.swing.JButton();
        WSLTbuttonJohnWick = new javax.swing.JButton();
        WSLTpanelschedJohnWick = new javax.swing.JPanel();
        WSLTlabelJohnWick = new javax.swing.JLabel();
        TYAlabelGenreCars = new javax.swing.JLabel();
        TYAlabelRTimeCars = new javax.swing.JLabel();
        TYAlabelSchedCars = new javax.swing.JLabel();
        WSLTbuttonReserveJohnWick = new javax.swing.JButton();
        WSLTlabelShowJohnWick = new javax.swing.JLabel();
        WSLTBabyDriver = new javax.swing.JPanel();
        WSLTdetailBabyDriver = new javax.swing.JButton();
        WSLTbuttonBabyDriver = new javax.swing.JButton();
        WSLTpanelschedBabyDriver = new javax.swing.JPanel();
        WSLTlabelBabyDriver = new javax.swing.JLabel();
        WSLTlabelGenreBabyDriver = new javax.swing.JLabel();
        WSLTlabelRTimeBabyDriver = new javax.swing.JLabel();
        WSLTlabelSchedBabyDriver = new javax.swing.JLabel();
        WSLTbuttonReserveBabyDriver = new javax.swing.JButton();
        WSLTlabelShowBabyDriver = new javax.swing.JLabel();
        WSLTBaywatch = new javax.swing.JPanel();
        WSLTdetailBaywatch = new javax.swing.JButton();
        WSLTbuttonBaywatch = new javax.swing.JButton();
        WSLTpanelschedBaywatch = new javax.swing.JPanel();
        WSLTlabelBaywatch = new javax.swing.JLabel();
        WSLTlabelGenreBaywatch = new javax.swing.JLabel();
        WSLTlabelRTimeBaywatch = new javax.swing.JLabel();
        WSLTlabelSchedBaywatch = new javax.swing.JLabel();
        WSLTbuttonReserveBaywatch = new javax.swing.JButton();
        WSLTlabelShowBaywatch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WSLTAmity.setBackground(new java.awt.Color(255, 255, 255));

        WSLTdetailAmity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        WSLTdetailAmity.setBorderPainted(false);
        WSLTdetailAmity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WSLTdetailAmityActionPerformed(evt);
            }
        });

        WSLTbuttonAmity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterAmityville.png"))); // NOI18N
        WSLTbuttonAmity.setBorderPainted(false);
        WSLTbuttonAmity.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonAmityvillePressed.png"))); // NOI18N
        WSLTbuttonAmity.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonAmityvilleRollover.png"))); // NOI18N

        WSLTpanelschedAmity.setBackground(new java.awt.Color(255, 255, 255));

        WSLTlabelAmity.setFont(new java.awt.Font("Novecento sans wide", 1, 12)); // NOI18N
        WSLTlabelAmity.setForeground(new java.awt.Color(34, 66, 180));
        WSLTlabelAmity.setText("AMITYVILLE: THE AWAKENING");

        WSLTlabelGenreAmity.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelGenreAmity.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelGenreAmity.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelGenreAmity.setText("HORROR| THRILLER");

        WSLTlabelRTimeAmity.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelRTimeAmity.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelRTimeAmity.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelRTimeAmity.setText("1 HOUR 37 MINUTES");

        WSLTlabelSchedAmity.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelSchedAmity.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        WSLTlabelSchedAmity.setForeground(new java.awt.Color(249, 115, 0));
        WSLTlabelSchedAmity.setText("SCHEDULE:");

        WSLTbuttonReserveAmity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        WSLTbuttonReserveAmity.setBorder(null);
        WSLTbuttonReserveAmity.setBorderPainted(false);
        WSLTbuttonReserveAmity.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        WSLTbuttonReserveAmity.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        WSLTlabelShowAmity.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelShowAmity.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelShowAmity.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelShowAmity.setText("01:00 PM");

        javax.swing.GroupLayout WSLTpanelschedAmityLayout = new javax.swing.GroupLayout(WSLTpanelschedAmity);
        WSLTpanelschedAmity.setLayout(WSLTpanelschedAmityLayout);
        WSLTpanelschedAmityLayout.setHorizontalGroup(
            WSLTpanelschedAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedAmityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTpanelschedAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSLTpanelschedAmityLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WSLTpanelschedAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WSLTlabelAmity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WSLTlabelGenreAmity)
                            .addComponent(WSLTlabelRTimeAmity)
                            .addComponent(WSLTlabelSchedAmity)
                            .addComponent(WSLTbuttonReserveAmity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(WSLTpanelschedAmityLayout.createSequentialGroup()
                        .addComponent(WSLTlabelShowAmity)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        WSLTpanelschedAmityLayout.setVerticalGroup(
            WSLTpanelschedAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedAmityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WSLTlabelAmity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelGenreAmity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelRTimeAmity)
                .addGap(26, 26, 26)
                .addComponent(WSLTlabelSchedAmity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelShowAmity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WSLTbuttonReserveAmity))
        );

        javax.swing.GroupLayout WSLTAmityLayout = new javax.swing.GroupLayout(WSLTAmity);
        WSLTAmity.setLayout(WSLTAmityLayout);
        WSLTAmityLayout.setHorizontalGroup(
            WSLTAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTAmityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTbuttonAmity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTdetailAmity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTpanelschedAmity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WSLTAmityLayout.setVerticalGroup(
            WSLTAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTAmityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTAmityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTpanelschedAmity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(WSLTAmityLayout.createSequentialGroup()
                        .addComponent(WSLTbuttonAmity, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WSLTdetailAmity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        WSLTJohnWick.setBackground(new java.awt.Color(255, 255, 255));

        WSLTdetailJohnWick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR16.png"))); // NOI18N
        WSLTdetailJohnWick.setBorderPainted(false);
        WSLTdetailJohnWick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WSLTdetailJohnWickActionPerformed(evt);
            }
        });

        WSLTbuttonJohnWick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterJohnWick2.png"))); // NOI18N
        WSLTbuttonJohnWick.setBorderPainted(false);
        WSLTbuttonJohnWick.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonJohnWick2Pressed.png"))); // NOI18N
        WSLTbuttonJohnWick.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonJohnWick2Rollover.png"))); // NOI18N

        WSLTpanelschedJohnWick.setBackground(new java.awt.Color(255, 255, 255));

        WSLTlabelJohnWick.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        WSLTlabelJohnWick.setForeground(new java.awt.Color(34, 66, 180));
        WSLTlabelJohnWick.setText("JOHN WICK 2");

        TYAlabelGenreCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelGenreCars.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelGenreCars.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelGenreCars.setText("CRIME | THRILLER");

        TYAlabelRTimeCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelRTimeCars.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        TYAlabelRTimeCars.setForeground(new java.awt.Color(102, 102, 102));
        TYAlabelRTimeCars.setText("2 HOURS 2 MINUTES");
        TYAlabelRTimeCars.setToolTipText("");

        TYAlabelSchedCars.setBackground(new java.awt.Color(255, 255, 255));
        TYAlabelSchedCars.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        TYAlabelSchedCars.setForeground(new java.awt.Color(249, 115, 0));
        TYAlabelSchedCars.setText("SCHEDULE:");

        WSLTbuttonReserveJohnWick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        WSLTbuttonReserveJohnWick.setBorder(null);
        WSLTbuttonReserveJohnWick.setBorderPainted(false);
        WSLTbuttonReserveJohnWick.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        WSLTbuttonReserveJohnWick.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        WSLTlabelShowJohnWick.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelShowJohnWick.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelShowJohnWick.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelShowJohnWick.setText("02:55 PM");

        javax.swing.GroupLayout WSLTpanelschedJohnWickLayout = new javax.swing.GroupLayout(WSLTpanelschedJohnWick);
        WSLTpanelschedJohnWick.setLayout(WSLTpanelschedJohnWickLayout);
        WSLTpanelschedJohnWickLayout.setHorizontalGroup(
            WSLTpanelschedJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTpanelschedJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSLTpanelschedJohnWickLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WSLTpanelschedJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WSLTlabelJohnWick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TYAlabelGenreCars)
                            .addComponent(TYAlabelRTimeCars)
                            .addComponent(TYAlabelSchedCars)
                            .addComponent(WSLTbuttonReserveJohnWick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(WSLTpanelschedJohnWickLayout.createSequentialGroup()
                        .addComponent(WSLTlabelShowJohnWick)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        WSLTpanelschedJohnWickLayout.setVerticalGroup(
            WSLTpanelschedJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WSLTlabelJohnWick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelGenreCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TYAlabelRTimeCars)
                .addGap(26, 26, 26)
                .addComponent(TYAlabelSchedCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelShowJohnWick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WSLTbuttonReserveJohnWick)
                .addContainerGap())
        );

        javax.swing.GroupLayout WSLTJohnWickLayout = new javax.swing.GroupLayout(WSLTJohnWick);
        WSLTJohnWick.setLayout(WSLTJohnWickLayout);
        WSLTJohnWickLayout.setHorizontalGroup(
            WSLTJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTbuttonJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTdetailJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTpanelschedJohnWick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WSLTJohnWickLayout.setVerticalGroup(
            WSLTJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WSLTbuttonJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTdetailJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(WSLTpanelschedJohnWick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        WSLTBabyDriver.setBackground(new java.awt.Color(255, 255, 255));

        WSLTdetailBabyDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        WSLTdetailBabyDriver.setBorderPainted(false);
        WSLTdetailBabyDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WSLTdetailBabyDriverActionPerformed(evt);
            }
        });

        WSLTbuttonBabyDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterBabyDriver.png"))); // NOI18N
        WSLTbuttonBabyDriver.setBorderPainted(false);
        WSLTbuttonBabyDriver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBabyDriverPressed.png"))); // NOI18N
        WSLTbuttonBabyDriver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBabyDriverRollover.png"))); // NOI18N

        WSLTpanelschedBabyDriver.setBackground(new java.awt.Color(255, 255, 255));

        WSLTlabelBabyDriver.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        WSLTlabelBabyDriver.setForeground(new java.awt.Color(34, 66, 180));
        WSLTlabelBabyDriver.setText("BABY DRIVER");

        WSLTlabelGenreBabyDriver.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelGenreBabyDriver.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelGenreBabyDriver.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelGenreBabyDriver.setText("ACTION | MUSICAL");

        WSLTlabelRTimeBabyDriver.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelRTimeBabyDriver.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelRTimeBabyDriver.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelRTimeBabyDriver.setText("2 HOURS 7 MINUTES");

        WSLTlabelSchedBabyDriver.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelSchedBabyDriver.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        WSLTlabelSchedBabyDriver.setForeground(new java.awt.Color(249, 115, 0));
        WSLTlabelSchedBabyDriver.setText("SCHEDULE:");

        WSLTbuttonReserveBabyDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        WSLTbuttonReserveBabyDriver.setBorder(null);
        WSLTbuttonReserveBabyDriver.setBorderPainted(false);
        WSLTbuttonReserveBabyDriver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        WSLTbuttonReserveBabyDriver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        WSLTlabelShowBabyDriver.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelShowBabyDriver.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelShowBabyDriver.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelShowBabyDriver.setText("05:15 PM");

        javax.swing.GroupLayout WSLTpanelschedBabyDriverLayout = new javax.swing.GroupLayout(WSLTpanelschedBabyDriver);
        WSLTpanelschedBabyDriver.setLayout(WSLTpanelschedBabyDriverLayout);
        WSLTpanelschedBabyDriverLayout.setHorizontalGroup(
            WSLTpanelschedBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTpanelschedBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSLTpanelschedBabyDriverLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WSLTpanelschedBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WSLTlabelBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WSLTlabelGenreBabyDriver)
                            .addComponent(WSLTlabelRTimeBabyDriver)
                            .addComponent(WSLTlabelSchedBabyDriver)
                            .addComponent(WSLTbuttonReserveBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(WSLTpanelschedBabyDriverLayout.createSequentialGroup()
                        .addComponent(WSLTlabelShowBabyDriver)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        WSLTpanelschedBabyDriverLayout.setVerticalGroup(
            WSLTpanelschedBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WSLTlabelBabyDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelGenreBabyDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelRTimeBabyDriver)
                .addGap(26, 26, 26)
                .addComponent(WSLTlabelSchedBabyDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelShowBabyDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WSLTbuttonReserveBabyDriver))
        );

        javax.swing.GroupLayout WSLTBabyDriverLayout = new javax.swing.GroupLayout(WSLTBabyDriver);
        WSLTBabyDriver.setLayout(WSLTBabyDriverLayout);
        WSLTBabyDriverLayout.setHorizontalGroup(
            WSLTBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTbuttonBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTdetailBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTpanelschedBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WSLTBabyDriverLayout.setVerticalGroup(
            WSLTBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTpanelschedBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(WSLTBabyDriverLayout.createSequentialGroup()
                        .addComponent(WSLTbuttonBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WSLTdetailBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        WSLTBaywatch.setBackground(new java.awt.Color(255, 255, 255));

        WSLTdetailBaywatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        WSLTdetailBaywatch.setBorderPainted(false);
        WSLTdetailBaywatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WSLTdetailBaywatchActionPerformed(evt);
            }
        });

        WSLTbuttonBaywatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterBaywatch.png"))); // NOI18N
        WSLTbuttonBaywatch.setBorderPainted(false);
        WSLTbuttonBaywatch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBaywatchPressed.png"))); // NOI18N
        WSLTbuttonBaywatch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBaywatchRollover.png"))); // NOI18N

        WSLTpanelschedBaywatch.setBackground(new java.awt.Color(255, 255, 255));

        WSLTlabelBaywatch.setFont(new java.awt.Font("Novecento sans wide", 1, 13)); // NOI18N
        WSLTlabelBaywatch.setForeground(new java.awt.Color(34, 66, 180));
        WSLTlabelBaywatch.setText("BAYWATCH");

        WSLTlabelGenreBaywatch.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelGenreBaywatch.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelGenreBaywatch.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelGenreBaywatch.setText("DRAMA | ACTION");

        WSLTlabelRTimeBaywatch.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelRTimeBaywatch.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelRTimeBaywatch.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelRTimeBaywatch.setText("1 HOUR 59 MINUTES");

        WSLTlabelSchedBaywatch.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelSchedBaywatch.setFont(new java.awt.Font("Novecento sans wide", 1, 10)); // NOI18N
        WSLTlabelSchedBaywatch.setForeground(new java.awt.Color(249, 115, 0));
        WSLTlabelSchedBaywatch.setText("SCHEDULE:");

        WSLTbuttonReserveBaywatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveDark.png"))); // NOI18N
        WSLTbuttonReserveBaywatch.setBorder(null);
        WSLTbuttonReserveBaywatch.setBorderPainted(false);
        WSLTbuttonReserveBaywatch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N
        WSLTbuttonReserveBaywatch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonReserveLight.png"))); // NOI18N

        WSLTlabelShowBaywatch.setBackground(new java.awt.Color(255, 255, 255));
        WSLTlabelShowBaywatch.setFont(new java.awt.Font("Novecento sans wide", 0, 10)); // NOI18N
        WSLTlabelShowBaywatch.setForeground(new java.awt.Color(102, 102, 102));
        WSLTlabelShowBaywatch.setText("07:30 PM");

        javax.swing.GroupLayout WSLTpanelschedBaywatchLayout = new javax.swing.GroupLayout(WSLTpanelschedBaywatch);
        WSLTpanelschedBaywatch.setLayout(WSLTpanelschedBaywatchLayout);
        WSLTpanelschedBaywatchLayout.setHorizontalGroup(
            WSLTpanelschedBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTpanelschedBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WSLTpanelschedBaywatchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WSLTpanelschedBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WSLTlabelBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WSLTlabelGenreBaywatch)
                            .addComponent(WSLTlabelRTimeBaywatch)
                            .addComponent(WSLTlabelSchedBaywatch)
                            .addComponent(WSLTbuttonReserveBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(WSLTpanelschedBaywatchLayout.createSequentialGroup()
                        .addComponent(WSLTlabelShowBaywatch)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        WSLTpanelschedBaywatchLayout.setVerticalGroup(
            WSLTpanelschedBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTpanelschedBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WSLTlabelBaywatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelGenreBaywatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelRTimeBaywatch)
                .addGap(26, 26, 26)
                .addComponent(WSLTlabelSchedBaywatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTlabelShowBaywatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WSLTbuttonReserveBaywatch))
        );

        javax.swing.GroupLayout WSLTBaywatchLayout = new javax.swing.GroupLayout(WSLTBaywatch);
        WSLTBaywatch.setLayout(WSLTBaywatchLayout);
        WSLTBaywatchLayout.setHorizontalGroup(
            WSLTBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTbuttonBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTdetailBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSLTpanelschedBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WSLTBaywatchLayout.setVerticalGroup(
            WSLTBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WSLTBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WSLTBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTpanelschedBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(WSLTBaywatchLayout.createSequentialGroup()
                        .addComponent(WSLTbuttonBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WSLTdetailBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelWSLTLayout = new javax.swing.GroupLayout(panelWSLT);
        panelWSLT.setLayout(panelWSLTLayout);
        panelWSLTLayout.setHorizontalGroup(
            panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWSLTLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTAmity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WSLTBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panelWSLTLayout.setVerticalGroup(
            panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWSLTLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WSLTAmity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WSLTJohnWick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelWSLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WSLTBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WSLTBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWSLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelWSLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WSLTdetailAmityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WSLTdetailAmityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WSLTdetailAmityActionPerformed

    private void WSLTdetailJohnWickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WSLTdetailJohnWickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WSLTdetailJohnWickActionPerformed

    private void WSLTdetailBabyDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WSLTdetailBabyDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WSLTdetailBabyDriverActionPerformed

    private void WSLTdetailBaywatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WSLTdetailBaywatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WSLTdetailBaywatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSLT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSLT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSLT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSLT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSLT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TYAlabelGenreCars;
    private javax.swing.JLabel TYAlabelRTimeCars;
    private javax.swing.JLabel TYAlabelSchedCars;
    private javax.swing.JPanel WSLTAmity;
    private javax.swing.JPanel WSLTBabyDriver;
    private javax.swing.JPanel WSLTBaywatch;
    private javax.swing.JPanel WSLTJohnWick;
    private javax.swing.JButton WSLTbuttonAmity;
    private javax.swing.JButton WSLTbuttonBabyDriver;
    private javax.swing.JButton WSLTbuttonBaywatch;
    private javax.swing.JButton WSLTbuttonJohnWick;
    private javax.swing.JButton WSLTbuttonReserveAmity;
    private javax.swing.JButton WSLTbuttonReserveBabyDriver;
    private javax.swing.JButton WSLTbuttonReserveBaywatch;
    private javax.swing.JButton WSLTbuttonReserveJohnWick;
    private javax.swing.JButton WSLTdetailAmity;
    private javax.swing.JButton WSLTdetailBabyDriver;
    private javax.swing.JButton WSLTdetailBaywatch;
    private javax.swing.JButton WSLTdetailJohnWick;
    private javax.swing.JLabel WSLTlabelAmity;
    private javax.swing.JLabel WSLTlabelBabyDriver;
    private javax.swing.JLabel WSLTlabelBaywatch;
    private javax.swing.JLabel WSLTlabelGenreAmity;
    private javax.swing.JLabel WSLTlabelGenreBabyDriver;
    private javax.swing.JLabel WSLTlabelGenreBaywatch;
    private javax.swing.JLabel WSLTlabelJohnWick;
    private javax.swing.JLabel WSLTlabelRTimeAmity;
    private javax.swing.JLabel WSLTlabelRTimeBabyDriver;
    private javax.swing.JLabel WSLTlabelRTimeBaywatch;
    private javax.swing.JLabel WSLTlabelSchedAmity;
    private javax.swing.JLabel WSLTlabelSchedBabyDriver;
    private javax.swing.JLabel WSLTlabelSchedBaywatch;
    private javax.swing.JLabel WSLTlabelShowAmity;
    private javax.swing.JLabel WSLTlabelShowBabyDriver;
    private javax.swing.JLabel WSLTlabelShowBaywatch;
    private javax.swing.JLabel WSLTlabelShowJohnWick;
    private javax.swing.JPanel WSLTpanelschedAmity;
    private javax.swing.JPanel WSLTpanelschedBabyDriver;
    private javax.swing.JPanel WSLTpanelschedBaywatch;
    private javax.swing.JPanel WSLTpanelschedJohnWick;
    private javax.swing.JPanel panelWSLT;
    // End of variables declaration//GEN-END:variables
}
