/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.ImageIcon;

import cinema.*;

/**
 *
 * @author christinecarylchen
 */
public class HomePage extends javax.swing.JFrame {

    //CINEMAS
    TYA TYA = new TYA();
    WSLT WSLT = new WSLT();
    Amphi Amphi = new Amphi();
    
    /**
     * Creates new form Main
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHomeBar = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonMovies = new javax.swing.JButton();
        buttonRegister = new javax.swing.JButton();
        lineGrey = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelSearchBar = new javax.swing.JPanel();
        comboBoxCinema = new javax.swing.JComboBox<>();
        buttonSearch = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        scrollpanelMovies = new javax.swing.JScrollPane();
        panelMovies = new javax.swing.JPanel();
        panelSpiderMan = new javax.swing.JPanel();
        detailSpiderman = new javax.swing.JButton();
        buttonSpiderman = new javax.swing.JButton();
        panelDespicableMe3 = new javax.swing.JPanel();
        detailDespicableMe3 = new javax.swing.JButton();
        buttonDespicableMe3 = new javax.swing.JButton();
        panelWonderWoman = new javax.swing.JPanel();
        buttonWonderWoman = new javax.swing.JButton();
        detailWonderWoman = new javax.swing.JButton();
        panelJohnWick = new javax.swing.JPanel();
        buttonJohnWick2 = new javax.swing.JButton();
        detailJohnWick2 = new javax.swing.JButton();
        panelBabyDriver = new javax.swing.JPanel();
        buttonBabyDriver = new javax.swing.JButton();
        detailBabyDriver = new javax.swing.JButton();
        panelBaywatch = new javax.swing.JPanel();
        buttonBaywatch = new javax.swing.JButton();
        detailBaywatch = new javax.swing.JButton();
        panelRoughNight = new javax.swing.JPanel();
        buttonRoughNight = new javax.swing.JButton();
        detailRoughNight = new javax.swing.JButton();
        panelBeforeIFall = new javax.swing.JPanel();
        buttonBeforeIFall = new javax.swing.JButton();
        detailBeforeIFall = new javax.swing.JButton();
        panelCars = new javax.swing.JPanel();
        buttonCars = new javax.swing.JButton();
        detailCars = new javax.swing.JButton();
        panelAmityville = new javax.swing.JPanel();
        buttonAmityville = new javax.swing.JButton();
        detailAmityville = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 825));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 0));

        panelHomeBar.setBackground(new java.awt.Color(255, 255, 255));
        panelHomeBar.setPreferredSize(new java.awt.Dimension(0, 25));

        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonHomeBlack.png"))); // NOI18N
        buttonHome.setBorder(null);
        buttonHome.setBorderPainted(false);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonHomeBlue.png"))); // NOI18N
        buttonHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonHomeBlue.png"))); // NOI18N
        buttonHome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonMovies.setBackground(new java.awt.Color(255, 255, 255));
        buttonMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonMoviesBlack.png"))); // NOI18N
        buttonMovies.setBorder(null);
        buttonMovies.setBorderPainted(false);
        buttonMovies.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonMoviesBlue.png"))); // NOI18N
        buttonMovies.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonMoviesBlue.png"))); // NOI18N
        buttonMovies.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        buttonMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMoviesActionPerformed(evt);
            }
        });

        buttonRegister.setBackground(new java.awt.Color(255, 255, 255));
        buttonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonRegister.png"))); // NOI18N
        buttonRegister.setBorder(null);
        buttonRegister.setBorderPainted(false);
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        lineGrey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/lineGrey.png"))); // NOI18N

        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonLogin.png"))); // NOI18N
        buttonLogin.setBorder(null);
        buttonLogin.setBorderPainted(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonLogo.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);

        javax.swing.GroupLayout panelHomeBarLayout = new javax.swing.GroupLayout(panelHomeBar);
        panelHomeBar.setLayout(panelHomeBarLayout);
        panelHomeBarLayout.setHorizontalGroup(
            panelHomeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeBarLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton1)
                .addGap(109, 109, 109)
                .addComponent(buttonHome)
                .addGap(41, 41, 41)
                .addComponent(buttonMovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineGrey, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogin)
                .addGap(108, 108, 108))
        );
        panelHomeBarLayout.setVerticalGroup(
            panelHomeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeBarLayout.createSequentialGroup()
                .addComponent(lineGrey, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelHomeBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHomeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMovies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        labelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/Title.png"))); // NOI18N

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(labelTitle)
                .addGap(0, 0, 0))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(labelTitle)
                .addGap(0, 0, 0))
        );

        panelSearchBar.setBackground(new java.awt.Color(255, 255, 255));

        comboBoxCinema.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCinema.setFont(new java.awt.Font("Novecento sans wide", 0, 13)); // NOI18N
        comboBoxCinema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Cinema (Optional)", "Teresa Yuchengco Auditorium", "William Shaw William Shaw Little Theatre", "Amphitheatre" }));
        comboBoxCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCinemaActionPerformed(evt);
            }
        });

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonSearchDark.png"))); // NOI18N
        buttonSearch.setBorder(null);
        buttonSearch.setBorderPainted(false);
        buttonSearch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonSearchLight.png"))); // NOI18N
        buttonSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHome/buttonSearchLight.png"))); // NOI18N
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchBarLayout = new javax.swing.GroupLayout(panelSearchBar);
        panelSearchBar.setLayout(panelSearchBarLayout);
        panelSearchBarLayout.setHorizontalGroup(
            panelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchBarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(comboBoxCinema, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(buttonSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchBarLayout.setVerticalGroup(
            panelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSearch)
                    .addComponent(comboBoxCinema))
                .addContainerGap())
        );

        scrollpanelMovies.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelSpiderMan.setBackground(new java.awt.Color(255, 255, 255));

        detailSpiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailSpiderman.setBorderPainted(false);
        detailSpiderman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailSpidermanMouseClicked(evt);
            }
        });
        detailSpiderman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailSpidermanActionPerformed(evt);
            }
        });

        buttonSpiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterSpiderman.png"))); // NOI18N
        buttonSpiderman.setBorderPainted(false);
        buttonSpiderman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonSpiderManPressed.png"))); // NOI18N
        buttonSpiderman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonSpiderManRollover.png"))); // NOI18N
        buttonSpiderman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpidermanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSpiderManLayout = new javax.swing.GroupLayout(panelSpiderMan);
        panelSpiderMan.setLayout(panelSpiderManLayout);
        panelSpiderManLayout.setHorizontalGroup(
            panelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSpiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailSpiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        panelSpiderManLayout.setVerticalGroup(
            panelSpiderManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSpiderManLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonSpiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailSpiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDespicableMe3.setBackground(new java.awt.Color(255, 255, 255));

        detailDespicableMe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonPG.png"))); // NOI18N
        detailDespicableMe3.setBorderPainted(false);
        detailDespicableMe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailDespicableMe3ActionPerformed(evt);
            }
        });

        buttonDespicableMe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterDespicableMe3.png"))); // NOI18N
        buttonDespicableMe3.setBorderPainted(false);
        buttonDespicableMe3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonDM3Pressed.png"))); // NOI18N
        buttonDespicableMe3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonDM3Rollover.png"))); // NOI18N

        javax.swing.GroupLayout panelDespicableMe3Layout = new javax.swing.GroupLayout(panelDespicableMe3);
        panelDespicableMe3.setLayout(panelDespicableMe3Layout);
        panelDespicableMe3Layout.setHorizontalGroup(
            panelDespicableMe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespicableMe3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDespicableMe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDespicableMe3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailDespicableMe3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelDespicableMe3Layout.setVerticalGroup(
            panelDespicableMe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespicableMe3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDespicableMe3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailDespicableMe3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelWonderWoman.setBackground(new java.awt.Color(255, 255, 255));

        buttonWonderWoman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterWonderWoman.png"))); // NOI18N
        buttonWonderWoman.setBorderPainted(false);
        buttonWonderWoman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonWonderWomanPressed.png"))); // NOI18N
        buttonWonderWoman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonWonderWomanRollover.png"))); // NOI18N

        detailWonderWoman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailWonderWoman.setBorderPainted(false);

        javax.swing.GroupLayout panelWonderWomanLayout = new javax.swing.GroupLayout(panelWonderWoman);
        panelWonderWoman.setLayout(panelWonderWomanLayout);
        panelWonderWomanLayout.setHorizontalGroup(
            panelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelWonderWomanLayout.setVerticalGroup(
            panelWonderWomanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWonderWomanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelJohnWick.setBackground(new java.awt.Color(255, 255, 255));

        buttonJohnWick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterJohnWick2.png"))); // NOI18N
        buttonJohnWick2.setBorderPainted(false);
        buttonJohnWick2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonJohnWick2Pressed.png"))); // NOI18N
        buttonJohnWick2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonJohnWick2Rollover.png"))); // NOI18N

        detailJohnWick2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR16.png"))); // NOI18N
        detailJohnWick2.setBorderPainted(false);

        javax.swing.GroupLayout panelJohnWickLayout = new javax.swing.GroupLayout(panelJohnWick);
        panelJohnWick.setLayout(panelJohnWickLayout);
        panelJohnWickLayout.setHorizontalGroup(
            panelJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJohnWick2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailJohnWick2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJohnWickLayout.setVerticalGroup(
            panelJohnWickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJohnWickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonJohnWick2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailJohnWick2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBabyDriver.setBackground(new java.awt.Color(255, 255, 255));

        buttonBabyDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterBabyDriver.png"))); // NOI18N
        buttonBabyDriver.setBorderPainted(false);
        buttonBabyDriver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBabyDriverPressed.png"))); // NOI18N
        buttonBabyDriver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBabyDriverRollover.png"))); // NOI18N

        detailBabyDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailBabyDriver.setBorderPainted(false);
        detailBabyDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBabyDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBabyDriverLayout = new javax.swing.GroupLayout(panelBabyDriver);
        panelBabyDriver.setLayout(panelBabyDriverLayout);
        panelBabyDriverLayout.setHorizontalGroup(
            panelBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBabyDriverLayout.setVerticalGroup(
            panelBabyDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBabyDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBaywatch.setBackground(new java.awt.Color(255, 255, 255));

        buttonBaywatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterBaywatch.png"))); // NOI18N
        buttonBaywatch.setBorderPainted(false);
        buttonBaywatch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBaywatchPressed.png"))); // NOI18N
        buttonBaywatch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBaywatchRollover.png"))); // NOI18N

        detailBaywatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailBaywatch.setBorderPainted(false);
        detailBaywatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBaywatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBaywatchLayout = new javax.swing.GroupLayout(panelBaywatch);
        panelBaywatch.setLayout(panelBaywatchLayout);
        panelBaywatchLayout.setHorizontalGroup(
            panelBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelBaywatchLayout.setVerticalGroup(
            panelBaywatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaywatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRoughNight.setBackground(new java.awt.Color(255, 255, 255));

        buttonRoughNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterRoughNight.png"))); // NOI18N
        buttonRoughNight.setBorderPainted(false);
        buttonRoughNight.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonRoughNightPressed.png"))); // NOI18N
        buttonRoughNight.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonRoughNightRollover.png"))); // NOI18N
        buttonRoughNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRoughNightActionPerformed(evt);
            }
        });

        detailRoughNight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR16.png"))); // NOI18N
        detailRoughNight.setBorderPainted(false);
        detailRoughNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailRoughNightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRoughNightLayout = new javax.swing.GroupLayout(panelRoughNight);
        panelRoughNight.setLayout(panelRoughNightLayout);
        panelRoughNightLayout.setHorizontalGroup(
            panelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoughNightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoughNightLayout.setVerticalGroup(
            panelRoughNightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoughNightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBeforeIFall.setBackground(new java.awt.Color(255, 255, 255));

        buttonBeforeIFall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterBeforeIFall.png"))); // NOI18N
        buttonBeforeIFall.setBorderPainted(false);
        buttonBeforeIFall.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBeforeIFallPressed.png"))); // NOI18N
        buttonBeforeIFall.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonBeforeIFallRollover.png"))); // NOI18N
        buttonBeforeIFall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeforeIFallActionPerformed(evt);
            }
        });

        detailBeforeIFall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailBeforeIFall.setBorderPainted(false);
        detailBeforeIFall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBeforeIFallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBeforeIFallLayout = new javax.swing.GroupLayout(panelBeforeIFall);
        panelBeforeIFall.setLayout(panelBeforeIFallLayout);
        panelBeforeIFallLayout.setHorizontalGroup(
            panelBeforeIFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeforeIFallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBeforeIFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBeforeIFall, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailBeforeIFall, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBeforeIFallLayout.setVerticalGroup(
            panelBeforeIFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeforeIFallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBeforeIFall, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailBeforeIFall, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCars.setBackground(new java.awt.Color(255, 255, 255));

        buttonCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterCars3.png"))); // NOI18N
        buttonCars.setBorderPainted(false);
        buttonCars.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonCars3Pressed.png"))); // NOI18N
        buttonCars.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonCars3Rollover.png"))); // NOI18N
        buttonCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarsActionPerformed(evt);
            }
        });

        detailCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonG.png"))); // NOI18N
        detailCars.setBorderPainted(false);
        detailCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailCarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCarsLayout = new javax.swing.GroupLayout(panelCars);
        panelCars.setLayout(panelCarsLayout);
        panelCarsLayout.setHorizontalGroup(
            panelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailCars, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCarsLayout.setVerticalGroup(
            panelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCars, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailCars, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAmityville.setBackground(new java.awt.Color(255, 255, 255));

        buttonAmityville.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posters/posterAmityville.png"))); // NOI18N
        buttonAmityville.setBorderPainted(false);
        buttonAmityville.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonAmityvillePressed.png"))); // NOI18N
        buttonAmityville.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRolloverPressed/buttonAmityvilleRollover.png"))); // NOI18N
        buttonAmityville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAmityvilleActionPerformed(evt);
            }
        });

        detailAmityville.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonRating/buttonR13.png"))); // NOI18N
        detailAmityville.setBorderPainted(false);
        detailAmityville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailAmityvilleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAmityvilleLayout = new javax.swing.GroupLayout(panelAmityville);
        panelAmityville.setLayout(panelAmityvilleLayout);
        panelAmityvilleLayout.setHorizontalGroup(
            panelAmityvilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmityvilleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAmityvilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAmityville, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailAmityville, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAmityvilleLayout.setVerticalGroup(
            panelAmityvilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmityvilleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAmityville, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailAmityville, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMoviesLayout = new javax.swing.GroupLayout(panelMovies);
        panelMovies.setLayout(panelMoviesLayout);
        panelMoviesLayout.setHorizontalGroup(
            panelMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoviesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSpiderMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDespicableMe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWonderWoman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJohnWick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBabyDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBaywatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRoughNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBeforeIFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAmityville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMoviesLayout.setVerticalGroup(
            panelMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoviesLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBaywatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBabyDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJohnWick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWonderWoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDespicableMe3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSpiderMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRoughNight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBeforeIFall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAmityville, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        scrollpanelMovies.setViewportView(panelMovies);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanelMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanelMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHomeBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(panelSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHomeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        panelTitle.setVisible(true);
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void comboBoxCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCinemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCinemaActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void buttonSpidermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpidermanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSpidermanActionPerformed

    private void detailDespicableMe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailDespicableMe3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailDespicableMe3ActionPerformed

    private void detailBabyDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBabyDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBabyDriverActionPerformed

    private void detailBaywatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBaywatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBaywatchActionPerformed

    private void detailRoughNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailRoughNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailRoughNightActionPerformed

    private void buttonRoughNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRoughNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRoughNightActionPerformed

    private void buttonBeforeIFallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeforeIFallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBeforeIFallActionPerformed

    private void detailBeforeIFallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBeforeIFallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBeforeIFallActionPerformed

    private void buttonCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCarsActionPerformed

    private void detailCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailCarsActionPerformed

    private void buttonAmityvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAmityvilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAmityvilleActionPerformed

    private void detailAmityvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailAmityvilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailAmityvilleActionPerformed

    private void detailSpidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailSpidermanMouseClicked
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_detailSpidermanMouseClicked

    private void detailSpidermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailSpidermanActionPerformed
        

// TODO add your handling code here:
    }//GEN-LAST:event_detailSpidermanActionPerformed

    private void buttonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoviesActionPerformed
       panelTitle.setVisible(false);
    }//GEN-LAST:event_buttonMoviesActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        if (comboBoxCinema.getSelectedIndex()==1){
            TYA.setVisible(true);
            TYA.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }   
        
        if (comboBoxCinema.getSelectedIndex()==2){
            WSLT.setVisible(true);
            WSLT.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }  
        
        if (comboBoxCinema.getSelectedIndex()==3){
            Amphi.setVisible(true);
            Amphi.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }  
       
    
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
             // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAmityville;
    private javax.swing.JButton buttonBabyDriver;
    private javax.swing.JButton buttonBaywatch;
    private javax.swing.JButton buttonBeforeIFall;
    private javax.swing.JButton buttonCars;
    private javax.swing.JButton buttonDespicableMe3;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonJohnWick2;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonMovies;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonRoughNight;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonSpiderman;
    private javax.swing.JButton buttonWonderWoman;
    private javax.swing.JComboBox<String> comboBoxCinema;
    private javax.swing.JButton detailAmityville;
    private javax.swing.JButton detailBabyDriver;
    private javax.swing.JButton detailBaywatch;
    private javax.swing.JButton detailBeforeIFall;
    private javax.swing.JButton detailCars;
    private javax.swing.JButton detailDespicableMe3;
    private javax.swing.JButton detailJohnWick2;
    private javax.swing.JButton detailRoughNight;
    private javax.swing.JButton detailSpiderman;
    private javax.swing.JButton detailWonderWoman;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lineGrey;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAmityville;
    private javax.swing.JPanel panelBabyDriver;
    private javax.swing.JPanel panelBaywatch;
    private javax.swing.JPanel panelBeforeIFall;
    private javax.swing.JPanel panelCars;
    private javax.swing.JPanel panelDespicableMe3;
    private javax.swing.JPanel panelHomeBar;
    private javax.swing.JPanel panelJohnWick;
    private javax.swing.JPanel panelMovies;
    private javax.swing.JPanel panelRoughNight;
    private javax.swing.JPanel panelSearchBar;
    private javax.swing.JPanel panelSpiderMan;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelWonderWoman;
    private javax.swing.JScrollPane scrollpanelMovies;
    // End of variables declaration//GEN-END:variables
}
